// trabalho5estacio/trabalho5estacio/clientes/livros-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'livros-angular';
}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary border-bottom border-warning">
  <div class="container">
    <button 
      class="navbar-toggler" 
      type="button" 
      data-bs-toggle="collapse" 
      data-bs-target="#navbarNav" 
      aria-controls="navbarNav" 
      aria-expanded="false" 
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link fw-bold" routerLink="/lista" routerLinkActive="active">Catálogo</a>
        </li>
        <li class="nav-item">
          <a class="nav-link fw-bold" routerLink="/dados" routerLinkActive="active">Novo</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container mt-4">
  <router-outlet></router-outlet>
</div>

// trabalho5estacio/trabalho5estacio/clientes/livros-react/src/App.tsx
import React from 'react';
import logo from './logo.svg';
import './App.css';
import { BrowserRouter as Router, Routes, Route, Link } from 'react-router-dom';
import LivroLista from './LivroLista';
import LivroDados from './LivroDados';

function App() {
  return (
    <Router>
      {/* Menu de navegação com BootStrap */}
      <nav className="navbar navbar-expand-sm navbar-light bg-warning">
        <div className="container-fluid">
          <Link className="navbar-brand text-primary" to="/">Livros</Link>
          <div className="collapse navbar-collapse" id="navbarNav">
            <ul className="navbar-nav">
              <li className="nav-item">
                <Link className="nav-link text-success" to="/">Catálogo</Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link text-danger" to="/dados">Novo</Link>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      {/* Definindo as rotas com BrowserRouter */}
      <div className="container mt-5 p-3 border rounded shadow-lg">
        <Routes>
          <Route path="/" element={<LivroLista />} />
          <Route path="/dados" element={<LivroDados />} />
        </Routes>
      </div>
    </Router>
  );
}

export default App;
