// trabalho5estacio/trabalho5estacio/clientes/livros-react/src/LivroDados.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import ControleLivros from './controle/ControleLivro';
import ControleEditora, { editoras } from './controle/ControleEditora';

// Instanciar controladores
const controleLivro = new ControleLivros();
const controleEditora = new ControleEditora(editoras);

const LivroDados = () => {
    // Definir vetor opcoes com as editoras
    const opcoes = controleEditora.getEditoras().map(editora => ({
        value: editora.codEditora,
        text: editora.nome
    }));

    // Definir estados para as propriedades
    const [titulo, setTitulo] = useState('');
    const [resumo, setResumo] = useState('');
    const [autores, setAutores] = useState('');
    const [codEditora, setCodEditora] = useState(opcoes[0].value);

    // Definir o hook navigate
    const navigate = useNavigate();

    // Método tratarCombo para a combo de editoras
    const tratarCombo = (event: React.ChangeEvent<HTMLSelectElement>) => {
        setCodEditora(Number(event.target.value));
    };

    // Método incluir
    const incluir = (event: React.FormEvent) => {
        event.preventDefault(); // Previne o comportamento padrão de submit

        // Instanciar o livro com código como string vazia e os valores do estado
        const livro = {
            codigo: "", // Identificador inicial vazio
            titulo: titulo,
            resumo: resumo,
            autores: autores.split('\n'), // Autores separados por linhas
            codEditora: codEditora
        };

        // Invocar o método incluir do controlador de livros
        controleLivro.incluir(livro).then(() => {
            // Redirecionar para a página de listagem após a inclusão
            navigate('/');
        });
    };

    // Retornar o formulário para inclusão do livro
    return (
        <main className="container mt-4">
            <h1 className="mb-4">Dados do Livro</h1>
            <form onSubmit={incluir}>
                <div className="mb-3">
                    <label className="form-label">Título</label>
                    <input 
                        type="text" 
                        className="form-control" 
                        value={titulo} 
                        onChange={(e) => setTitulo(e.target.value)} 
                        required 
                    />
                </div>

                <div className="mb-3">
                    <label className="form-label">Resumo</label>
                    <textarea 
                        className="form-control" 
                        value={resumo} 
                        onChange={(e) => setResumo(e.target.value)} 
                        required 
                    />
                </div>

                <div className="mb-3">
                    <label className="form-label">Autores (um por linha)</label>
                    <textarea 
                        className="form-control" 
                        value={autores} 
                        onChange={(e) => setAutores(e.target.value)} 
                        required 
                    />
                </div>

                {/* Lista de seleção para editoras */}
                <div className="mb-3">
                    <label className="form-label">Editora</label>
                    <select 
                        className="form-select" 
                        value={codEditora} 
                        onChange={tratarCombo}
                    >
                        {opcoes.map((opcao) => (
                            <option key={opcao.value} value={opcao.value}>
                                {opcao.text}
                            </option>
                        ))}
                    </select>
                </div>

                {/* Botão de submissão */}
                <button type="submit" className="btn btn-primary">
                    Salvar Dados
                </button>
            </form>
        </main>
    );
};

export default LivroDados;

// trabalho5estacio/trabalho5estacio/clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro = new Livro();       
  public autoresForm: string = '';         
  public editoras: Array<Editora> = [];    
  private servEditora: ControleEditoraService;
  private servLivros: ControleLivrosService;
  private router: Router;

  constructor(servEditora: ControleEditoraService, servLivros: ControleLivrosService, router: Router) {
    this.servEditora = servEditora;
    this.servLivros = servLivros;
    this.router = router;
  }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split('\n');
    
    // Chama o método incluir do serviço ControleLivrosService
    this.servLivros.incluir(this.livro).then(() => {
      // Navega para a página de lista após o sucesso da inclusão
      this.router.navigateByUrl('/lista');
    }).catch((erro) => {
      console.error('Erro ao incluir livro:', erro);
      // Aqui você pode adicionar um tratamento de erro, se necessário
    });
  };
}
<main class="container mt-4">
  <h1 class="mb-4 text-center text-primary">Dados do Livro</h1>
  <form (submit)="incluir()" ngNativeValidate>
    <div class="row">
      <div class="col-md-6 mb-3">
        <label for="titulo" class="form-label fw-bold">Título</label>
        <input
          type="text"
          id="titulo"
          class="form-control"
          [(ngModel)]="livro.titulo"
          name="titulo"
          placeholder="Digite o título do livro"
          required
        />
      </div>

      <div class="col-md-6 mb-3">
        <label for="editora" class="form-label fw-bold">Editora</label>
        <select
          id="editora"
          class="form-select"
          [(ngModel)]="livro.codEditora"
          name="editora"
          required
        >
          <option value="" disabled selected>Selecione uma editora</option>
          <option *ngFor="let editora of editoras" [value]="editora.codEditora">
            {{ editora.nome }}
          </option>
        </select>
      </div>
    </div>

    <div class="mb-3">
      <label for="resumo" class="form-label fw-bold">Resumo</label>
      <textarea
        id="resumo"
        class="form-control"
        [(ngModel)]="livro.resumo"
        name="resumo"
        rows="3"
        placeholder="Escreva um breve resumo do livro"
      ></textarea>
    </div>

    <div class="mb-3">
      <label for="autores" class="form-label fw-bold">Autores (1 por linha)</label>
      <textarea
        id="autores"
        class="form-control"
        [(ngModel)]="autoresForm"
        name="autores"
        rows="3"
        placeholder="Digite os nomes dos autores, um por linha"
      ></textarea>
    </div>

    <div class="text-center">
      <button type="submit" class="btn btn-primary btn-lg px-5">Salvar Dados</button>
    </div>
  </form>
</main>
