// trabalho5estacio/trabalho5estacio/clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro = new Livro();       
  public autoresForm: string = '';         
  public editoras: Array<Editora> = [];    
  private servEditora: ControleEditoraService;
  private servLivros: ControleLivrosService;
  private router: Router;

  constructor(servEditora: ControleEditoraService, servLivros: ControleLivrosService, router: Router) {
    this.servEditora = servEditora;
    this.servLivros = servLivros;
    this.router = router;
  }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split('\n');
    
   
    this.servLivros.incluir(this.livro).then(() => {
    
      this.router.navigateByUrl('/lista');
    }).catch((erro) => {
      console.error('Erro ao incluir livro:', erro);
   
    });
  };
}

<main class="container mt-4">
  <h1 class="mb-4 text-center text-primary">Dados do Livro</h1>
  <form (submit)="incluir()" ngNativeValidate>
    <div class="row">
      <div class="col-md-6 mb-3">
        <label for="titulo" class="form-label fw-bold">Título</label>
        <input
          type="text"
          id="titulo"
          class="form-control"
          [(ngModel)]="livro.titulo"
          name="titulo"
          placeholder="Digite o título do livro"
          required
        />
      </div>

      <div class="col-md-6 mb-3">
        <label for="editora" class="form-label fw-bold">Editora</label>
        <select
          id="editora"
          class="form-select"
          [(ngModel)]="livro.codEditora"
          name="editora"
          required
        >
          <option value="" disabled selected>Selecione uma editora</option>
          <option *ngFor="let editora of editoras" [value]="editora.codEditora">
            {{ editora.nome }}
          </option>
        </select>
      </div>
    </div>

    <div class="mb-3">
      <label for="resumo" class="form-label fw-bold">Resumo</label>
      <textarea
        id="resumo"
        class="form-control"
        [(ngModel)]="livro.resumo"
        name="resumo"
        rows="3"
        placeholder="Escreva um breve resumo do livro"
      ></textarea>
    </div>

    <div class="mb-3">
      <label for="autores" class="form-label fw-bold">Autores (1 por linha)</label>
      <textarea
        id="autores"
        class="form-control"
        [(ngModel)]="autoresForm"
        name="autores"
        rows="3"
        placeholder="Digite os nomes dos autores, um por linha"
      ></textarea>
    </div>

    <div class="text-center">
      <button type="submit" class="btn btn-primary btn-lg px-5">Salvar Dados</button>
    </div>
  </form>
</main>

// trabalho5estacio/trabalho5estacio/clientes/livros-next/pages/LivroDados.tsx
import type { NextPage } from 'next';
import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import { Menu } from '../componentes/Menu'; 
import { useRouter } from 'next/router';
import ControleEditora, { editoras } from '../classes/controle/ControleEditora'; 
import ControleLivro from '../classes/controle/ControleLivro'; 
import Livro from '../classes/modelo/Livro';

const LivroDados: React.FC = () => {
    const controleEditora = new ControleEditora(editoras); 
    const controleLivros = new ControleLivro(); 
    const router = useRouter(); 

    const [opcoes, setOpcoes] = useState<{ value: number; text: String }[]>([]);
    const [titulo, setTitulo] = useState<string>(''); 
    const [resumo, setResumo] = useState<string>(''); 
    const [autores, setAutores] = useState<string>(''); 
    const [codEditora, setCodEditora] = useState<number>(0);

    useEffect(() => {
        const carregarEditoras = async () => {
            const editoras = await controleEditora.getEditoras();
            setOpcoes(editoras.map(({ codEditora, nome }) => ({ value: codEditora, text: nome }))); 
            if (editoras.length > 0) {
                setCodEditora(editoras[0].codEditora); 
            }
        };

        carregarEditoras();
    }, []);

    const tratarCombo = (evento: React.ChangeEvent<HTMLSelectElement>) => {
        setCodEditora(Number(evento.target.value)); 
    };

    const incluir = async (evento: React.FormEvent<HTMLFormElement>) => {
        evento.preventDefault(); 
        const livro: Livro = new Livro(
            codEditora,
            titulo,
            resumo,
            autores.split('\n'), 
        );

        controleLivros.incluir(livro).then((sucesso) => {
            console.log('Livro incluído com sucesso:', sucesso);
            if (sucesso) {
                router.push('/LivroLista');
            } else {
                console.log('Erro ao incluir livro');
            }
        });
    };

    return (
        <div className="container mt-4">
            <Head>
                <title>Incluir Livro</title>
            </Head>
            <Menu />
            <main className="col-md-8 mx-auto">
                <h1 className="text-center mb-4 text-primary">Dados do Livro</h1>
                <form onSubmit={incluir}>
                    <div className="mb-3">
                        <label htmlFor="titulo" className="form-label">Título</label>
                        <input
                            type="text"
                            className="form-control"
                            id="titulo"
                            value={titulo}
                            onChange={(e) => setTitulo(e.target.value)}
                            required
                        />
                    </div>
                    <div className="mb-3">
                        <label htmlFor="resumo" className="form-label">Resumo</label>
                        <textarea
                            className="form-control"
                            id="resumo"
                            value={resumo}
                            onChange={(e) => setResumo(e.target.value)}
                            required
                        />
                    </div>
                    <div className="mb-3">
                        <label htmlFor="autores" className="form-label">Autores (separados por linha)</label>
                        <textarea
                            className="form-control"
                            id="autores"
                            value={autores}
                            onChange={(e) => setAutores(e.target.value)}
                            required
                        />
                    </div>
                    <div className="mb-3">
                        <label htmlFor="codEditora" className="form-label">Editora</label>
                        <select
                            id="codEditora"
                            className="form-select"
                            value={codEditora}
                            onChange={tratarCombo}
                            required
                        >
                            {opcoes.map(opcao => (
                                <option key={opcao.value} value={opcao.value}>
                                    {opcao.text}
                                </option>
                            ))}
                        </select>
                    </div>
                    <button type="submit" className="btn btn-primary w-100 mt-3">Salvar Dados</button>
                </form>
            </main>
        </div>
    );
};

export default LivroDados;
